language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install: 
  - pip install Flask
  - export PYTHONPATH=$PYTHONPATH:`pwd` 
  
# command to run tests
script: 
  - cd synapyse/samples/impl/
  - python car_evaluation.py
